// examples/client/ngx/src/app/home/home.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-home',
    templateUrl: './home.component.html',
    styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

    stars: number;
    forks: number;
    issues: number;

    constructor(private http: HttpClient) {
    }

    ngOnInit() {
        this
            .http
            .get('https://api.github.com/repos/yisraelx/authllizer')
            .subscribe((response: any) => {
                if (response) {
                    if (response.stargazers_count) {
                        this.stars = response.stargazers_count;
                    }
                    if (response.forks) {
                        this.forks = response.forks;
                    }
                    if (response.open_issues) {
                        this.issues = response.open_issues;
                    }
                }
            });
    }

}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">Home Page</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-6">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                        tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                        fermentum massa justo sit amet risus. Etiam porta sem malesuada
                        magna mollis euismod. Donec sed odio dui.</p>
                    <p><a class="btn btn-primary" href="#">View details » </a></p>
                </div>
                <div class="col-sm-6">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                        tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                        fermentum massa justo sit amet risus. Etiam porta sem malesuada
                        magna mollis euismod. Donec sed odio dui.</p>
                    <p><a class="btn btn-primary" href="#">View details »</a></p>
                </div>
            </div>
        </div>
        <div class="panel-footer text-center">
            <ul class="list-inline">
                <li><i class="fa fa-star"></i> {{stars | number}} stars</li>
                <li><i class="fa fa-code-fork"></i> {{forks | number}} forks</li>
                <li><i class="fa fa-exclamation-circle"></i> {{issues | number}} issues</li>
            </ul>
        </div>
    </div>
</div>
<div class="text-center">
    <a class="btn btn-default" href="https://github.com/yisraelx/authllizer"><i class="fa fa-github"></i> GitHub
        project</a>
    <a class="btn btn-default" href="https://github.com/yisraelx/authllizer/issues/new"><i class="fa fa-bug"></i> Report
        issue</a>
</div>

// examples/client/vue/src/app/home/home.component.ts
import axios, { AxiosResponse } from 'axios';
import Vue from 'vue';
import Component from 'vue-class-component';

@Component({
    templateUrl: './home.component.html'
})
export class HomeComponent extends Vue {

    stars = '';
    forks = '';
    issues = '';

    mounted() {
        axios
            .get('https://api.github.com/repos/yisraelx/authllizer')
            .then(({ data }: AxiosResponse) => {
                if (data) {
                    if (data.stargazers_count) {
                        this.stars = data.stargazers_count;
                    }
                    if (data.forks) {
                        this.forks = data.forks;
                    }
                    if (data.open_issues) {
                        this.issues = data.open_issues;
                    }
                }
            });
    }

}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">Home Page</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-6">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor
                        mauris
                        condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna
                        mollis
                        euismod. Donec sed odio dui.</p>
                    <p><a class="btn btn-primary" href="#">View details »</a></p>
                </div>
                <div class="col-sm-6">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor
                        mauris
                        condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna
                        mollis
                        euismod. Donec sed odio dui.</p>
                    <p><a class="btn btn-primary" href="#">View details »</a></p>
                </div>
            </div>
        </div>
        <div class="panel-footer text-center">
            <ul class="list-inline">
                <li><i class="fa fa-star"></i> {{stars}} stars</li>
                <li><i class="fa fa-code-fork"></i> {{forks}} forks</li>
                <li><i class="fa fa-exclamation-circle"></i> {{issues}} issues</li>
            </ul>
        </div>
    </div>
    <div class="text-center">
        <a class="btn btn-default" href="https://github.com/yisraelx/authllizer"><i class="fa fa-github"></i> GitHub
            project</a>
        <a class="btn btn-default" href="https://github.com/yisraelx/authllizer/issues/new"><i class="fa fa-bug"></i>
            Report
            issue</a>
    </div>
</div>
