// examples/client/ngx/src/app/signin/signin.component.ts
import { HttpErrorResponse } from '@angular/common/http';
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { Authllizer } from '@authllizer/core';
import { ToastrService } from 'ngx-toastr';

export interface ISignInUser {
    email?: string;
    password?: string;
}

@Component({
    selector: 'app-signin',
    templateUrl: './signin.component.html',
    styleUrls: ['./signin.component.css']
})
export class SignInComponent {

    user: ISignInUser = {};

    constructor(private auth: Authllizer, private toastr: ToastrService, private router: Router) {
    }

    async signIn() {
        try {
            await this.auth.signIn(this.user);
            await this.router.navigateByUrl('/');
            this.toastr.success('You have successfully signed in!');
        } catch (response) {
            let { error, message }: HttpErrorResponse = response;
            this.toastr.error((error && error.message) || message);
        }
    }

    async authenticate(provider: string) {
        try {
            await this.auth.authenticate(provider);
            await this.router.navigateByUrl('/');
            this.toastr.success(`You have successfully signed in with ${ provider }!`);
        } catch (response) {
            let { error, message }: HttpErrorResponse = response;
            this.toastr.error((error && error.message) || message);
        }
    }

}

<div class="container">
    <div class="row">
        <div class="center-form panel">
            <div class="panel-body">
                <h2 class="text-center">Sign in</h2>
                <form #loginForm="ngForm" (ngSubmit)="signIn()" method="post">
                    <div [class.has-error]="email.invalid && email.dirty" class="form-group has-feedback">
                        <input #email [(ngModel)]="user.email" autofocus class="form-control input-lg" email id="email"
                               name="email"
                               placeholder="Email" required type="email">
                        <span class="fa fa-at form-control-feedback"></span>
                        <div *ngIf="email.invalid && (email.dirty || email.touched)" class="help-block text-danger">
                            <div *ngIf="email.errors.required">Your email address is required.</div>
                            <div *ngIf="email.errors.email">Your email address is invalid.</div>
                        </div>
                    </div>
                    <div [class.has-error]="password.invalid && password.dirty" class="form-group has-feedback">
                        <input #password [(ngModel)]="user.password" class="form-control input-lg" id="password"
                               name="password" placeholder="Password"
                               required type="password">
                        <span class="fa fa-key form-control-feedback"></span>
                        <div *ngIf="password.invalid && (password.dirty || password.touched)"
                             class="help-block text-danger">
                            <div *ngIf="password.errors.required">Password is required.</div>
                        </div>
                    </div>
                    <button [disabled]="loginForm.form.invalid" class="btn btn-lg  btn-block btn-success" type="submit">
                        Sign in
                    </button>
                    <br/>
                    <p class="text-center text-muted">
                        <small>Don't have an account yet? <a routerLink="/signup">Sign up</a></small>
                    </p>
                    <div class="signup-or-separator">
                        <h6 class="text">or</h6>
                        <hr>
                    </div>
                </form>
                <button (click)="authenticate('bitbucket')" class="btn btn-block btn-bitbucket">
                    <i class="fa fa-bitbucket"></i> Sign in with Bitbucket
                </button>
                <button (click)="authenticate('facebook')" class="btn btn-block btn-facebook">
                    <i class="fa fa-facebook"></i> Sign in with Facebook
                </button>
                <button (click)="authenticate('foursquare')" class="btn btn-block btn-foursquare">
                    <i class="fa fa-foursquare"></i> Sign in with Foursquare
                </button>
                <button (click)="authenticate('github')" class="btn btn-block btn-github">
                    <i class="fa fa-github"></i> Sign in with GitHub
                </button>
                <button (click)="authenticate('google')" class="btn btn-block btn-google">
                    <i class="fa fa-google"></i>Sign in with Google
                </button>
                <button (click)="authenticate('instagram')" class="btn btn-block btn-instagram">
                    <i class="fa fa-instagram"></i> Sign in with Instagram
                </button>
                <button (click)="authenticate('linkedin')" class="btn btn-block btn-linkedin">
                    <i class="fa fa-linkedin"></i> Sign in with LinkedIn
                </button>
                <button (click)="authenticate('live')" class="btn btn-block btn-live">
                    <i class="fa fa-windows"></i> Sign in with Windows Live
                </button>
                <button (click)="authenticate('reddit')" class="btn btn-block btn-reddit">
                    <i class="fa fa-reddit"></i> Sign in with Reddit
                </button>
                <button (click)="authenticate('spotify')" class="btn btn-block btn-spotify">
                    <i class="fa fa-spotify"></i> Sign in with Spotify
                </button>
                <button (click)="authenticate('twitch')" class="btn btn-block btn-twitch">
                    <i class="fa fa-twitch"></i> Sign in with Twitch
                </button>
                <button (click)="authenticate('twitter')" class="btn btn-block btn-twitter">
                    <i class="fa fa-twitter"></i> Sign in with Twitter
                </button>
                <button (click)="authenticate('vk')" class="btn btn-block btn-vk">
                    <i class="fa fa-vk"></i> Sign in with Vk
                </button>
                <button (click)="authenticate('wordpress')" class="btn btn-block btn-wordpress">
                    <i class="fa fa-wordpress"></i> Sign in with Wordpress
                </button>
                <button (click)="authenticate('yahoo')" class="btn btn-block btn-yahoo">
                    <i class="fa fa-yahoo"></i> Sign in with Yahoo
                </button>
            </div>
        </div>
    </div>
</div>

// examples/client/vue/src/app/signin/signin.component.ts
import { AxiosError } from 'axios';
import Vue from 'vue';
import Component from 'vue-class-component';

export interface ISignInUser {
    email?: string;
    password?: string;
}

@Component({
    templateUrl: './signin.component.html'
})
export class SignInComponent extends Vue {

    user: ISignInUser = {};

    async signIn() {
        let valid = await this.$validator.validateAll();
        if (!valid) {
            return;
        }

        this
            .$auth
            .signIn(this.user)
            .then(() => {
                this.$toasted.success('You have successfully signed in!');
                this.$router.push('/');
            })
            .catch((error: AxiosError) => {
                let {response, message}: AxiosError = error;
                this.$toasted.error((response && ((response.data && response.data.message) || response.statusText)) || message);
            });
    }

    authenticate(provider: string) {
        this
            .$auth
            .authenticate(provider)
            .then(() => {
                this.$toasted.success(`You have successfully signed in with ${ provider }!`);
                this.$router.push('/');
            })
            .catch((error: AxiosError) => {
                let {response, message}: AxiosError = error;
                this.$toasted.error((response && ((response.data && response.data.message) || response.statusText)) || message);
            });
    }

}

<div class="container">
    <div class="row">
        <div class="center-form panel">
            <div class="panel-body">
                <h2 class="text-center">Sign in</h2>
                <form @submit.prevent="signIn()" name="signinForm">
                    <div :class="{ 'has-error' : errors.has('email') }" class="form-group has-feedback">
                        <input class="form-control input-lg" name="email" placeholder="Email" type="text"
                               v-model="user.email"
                               v-validate="{ required: true, email: true}">
                        <span class="fa fa-at form-control-feedback"></span>
                        <div class="help-block text-danger"
                             v-show="errors.has('email')">{{ errors.first('email') }}</div>
                    </div>
                    <div :class="{ 'has-error' : errors.has('password') }" class="form-group has-feedback">
                        <input class="form-control input-lg" name="password" placeholder="Password" type="password"
                               v-model="user.password" v-validate="{ required: true }">
                        <span class="fa fa-key form-control-feedback"></span>
                        <div class="help-block text-danger"
                             v-show="errors.has('password')">{{ errors.first('password') }}</div>
                    </div>
                    <button :disabled="!!errors.count()" class="btn btn-lg  btn-block btn-success" type="submit">Sign
                        in
                    </button>
                    <br/>
                    <p class="text-center text-muted">
                        <small>Don't have an account yet?
                            <router-link to="/signup">Sign up</router-link>
                        </small>
                    </p>
                    <div class="signup-or-separator">
                        <h6 class="text">or</h6>
                        <hr>
                    </div>
                </form>
                <button @click="authenticate('bitbucket')" class="btn btn-block btn-bitbucket">
                    <i class="fa fa-bitbucket"></i> Sign in with Bitbucket
                </button>
                <button @click="authenticate('facebook')" class="btn btn-block btn-facebook">
                    <i class="fa fa-facebook"></i> Sign in with Facebook
                </button>
                <button @click="authenticate('foursquare')" class="btn btn-block btn-foursquare">
                    <i class="fa fa-foursquare"></i> Sign in with Foursquare
                </button>
                <button @click="authenticate('github')" class="btn btn-block btn-github">
                    <i class="fa fa-github"></i> Sign in with GitHub
                </button>
                <button @click="authenticate('google')" class="btn btn-block btn-google">
                    <i class="fa fa-google"></i>Sign in with Google
                </button>
                <button @click="authenticate('instagram')" class="btn btn-block btn-instagram">
                    <i class="fa fa-instagram"></i> Sign in with Instagram
                </button>
                <button @click="authenticate('linkedin')" class="btn btn-block btn-linkedin">
                    <i class="fa fa-linkedin"></i> Sign in with LinkedIn
                </button>
                <button @click="authenticate('live')" class="btn btn-block btn-live">
                    <i class="fa fa-windows"></i> Sign in with Windows Live
                </button>
                <button @click="authenticate('reddit')" class="btn btn-block btn-reddit">
                    <i class="fa fa-reddit"></i> Sign in with Reddit
                </button>
                <button @click="authenticate('spotify')" class="btn btn-block btn-spotify">
                    <i class="fa fa-spotify"></i> Sign in with Spotify
                </button>
                <button @click="authenticate('twitch')" class="btn btn-block btn-twitch">
                    <i class="fa fa-twitch"></i> Sign in with Twitch
                </button>
                <button @click="authenticate('twitter')" class="btn btn-block btn-twitter">
                    <i class="fa fa-twitter"></i> Sign in with Twitter
                </button>
                <button @click="authenticate('vk')" class="btn btn-block btn-vk">
                    <i class="fa fa-vk"></i> Sign in with Vk
                </button>
                <button @click="authenticate('wordpress')" class="btn btn-block btn-wordpress">
                    <i class="fa fa-wordpress"></i> Sign in with Wordpress
                </button>
                <button @click="authenticate('yahoo')" class="btn btn-block btn-yahoo">
                    <i class="fa fa-yahoo"></i> Sign in with Yahoo
                </button>
            </div>
        </div>
    </div>
</div>
